#############################################################################
# Makefile for building: imacsLKAS
# Generated by qmake (2.01a) (Qt 4.8.7) on: wo feb. 19 14:38:26 2020
# Project:  cppVrepLKAS.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt4/bin/qmake -o Makefile cppVrepLKAS.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DNON_MATLAB_PARSING -DMAX_EXT_API_CONNECTIONS=255 -DDO_NOT_USE_SHARED_MEMORY -DHALIDE_NO_JPEG -D_GLIBCXX_USE_CXX11_ABI=0 -DQT_NO_DEBUG
CFLAGS        = -m64 -pipe -Wall -Wno-strict-aliasing -Wno-unused-parameter -Wno-unused-but-set-variable -Wno-unused-local-typedefs -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -Wall -Wno-unused-parameter -Wno-strict-aliasing -Wno-empty-body -Wno-write-strings -g -Wno-unused-but-set-variable -Wno-unused-local-typedefs -Wno-narrowing -std=c++11 -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4 -I$(PWD)/externalApps/vrep/programming/include -I$(PWD)/externalApps/vrep/programming/remoteApi -I$(PWD)/externalApps/eigen -I$(PWD)/src/cpp_vrep_api -I$(PWD)/include -I/usr/lib/pkgconfig -I$(PWD)/src/LaneDetection_and_Control -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -lrt -ldl -lm `pkg-config opencv --cflags --libs` -L/usr/lib -L/usr/lib/pkgconfig -L/home/sajid/apps/opencv -ljpeg `libpng-config --cflags --ldflags` -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/x86_64-linux-gnu/qt4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = $(PWD)/obj/

####### Files

SOURCES       = $(PWD)/src/cpp_vrep_api/cpp_vrep_framework.cpp \
		$(PWD)/src/cpp_vrep_api/my_vrep_api.cpp \
		$(PWD)/src/LaneDetection_and_Control/lane_detection.cpp \
		$(PWD)/src/LaneDetection_and_Control/lateralcontrol_multiple.cpp \
		$(PWD)/src/cpp_vrep_api/utils.cpp \
		$(PWD)/externalApps/vrep/programming/remoteApi/extApi.c \
		$(PWD)/externalApps/vrep/programming/remoteApi/extApiPlatform.c \
		$(PWD)/externalApps/vrep/programming/common/shared_memory.c 
OBJECTS       = $(PWD)/obj/cpp_vrep_framework.o \
		$(PWD)/obj/my_vrep_api.o \
		$(PWD)/obj/lane_detection.o \
		$(PWD)/obj/lateralcontrol_multiple.o \
		$(PWD)/obj/utils.o \
		$(PWD)/obj/extApi.o \
		$(PWD)/obj/extApiPlatform.o \
		$(PWD)/obj/shared_memory.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		cppVrepLKAS.pro
QMAKE_TARGET  = imacsLKAS
DESTDIR       = 
TARGET        = imacsLKAS

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: cppVrepLKAS.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf
	$(QMAKE) -o Makefile cppVrepLKAS.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
qmake:  FORCE
	@$(QMAKE) -o Makefile cppVrepLKAS.pro

dist: 
	@$(CHK_DIR_EXISTS) $(PWD)/obj/imacsLKAS1.0.0 || $(MKDIR) $(PWD)/obj/imacsLKAS1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) $(PWD)/obj/imacsLKAS1.0.0/ && $(COPY_FILE) --parents $(PWD)/externalApps/vrep/programming/remoteApi/extApi.h $(PWD)/externalApps/vrep/programming/remoteApi/extApiPlatform.h $(PWD)/externalApps/vrep/programming/include/shared_memory.h $(PWD)/obj/imacsLKAS1.0.0/ && $(COPY_FILE) --parents $(PWD)/src/cpp_vrep_api/cpp_vrep_framework.cpp $(PWD)/src/cpp_vrep_api/my_vrep_api.cpp $(PWD)/src/LaneDetection_and_Control/lane_detection.cpp $(PWD)/src/LaneDetection_and_Control/lateralcontrol_multiple.cpp $(PWD)/src/cpp_vrep_api/utils.cpp $(PWD)/externalApps/vrep/programming/remoteApi/extApi.c $(PWD)/externalApps/vrep/programming/remoteApi/extApiPlatform.c $(PWD)/externalApps/vrep/programming/common/shared_memory.c $(PWD)/obj/imacsLKAS1.0.0/ && (cd `dirname $(PWD)/obj/imacsLKAS1.0.0` && $(TAR) imacsLKAS1.0.0.tar imacsLKAS1.0.0 && $(COMPRESS) imacsLKAS1.0.0.tar) && $(MOVE) `dirname $(PWD)/obj/imacsLKAS1.0.0`/imacsLKAS1.0.0.tar.gz . && $(DEL_FILE) -r $(PWD)/obj/imacsLKAS1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

$(PWD)/obj/cpp_vrep_framework.o: $(PWD)/src/cpp_vrep_api/cpp_vrep_framework.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(PWD)/obj/cpp_vrep_framework.o $(PWD)/src/cpp_vrep_api/cpp_vrep_framework.cpp

$(PWD)/obj/my_vrep_api.o: $(PWD)/src/cpp_vrep_api/my_vrep_api.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(PWD)/obj/my_vrep_api.o $(PWD)/src/cpp_vrep_api/my_vrep_api.cpp

$(PWD)/obj/lane_detection.o: $(PWD)/src/LaneDetection_and_Control/lane_detection.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(PWD)/obj/lane_detection.o $(PWD)/src/LaneDetection_and_Control/lane_detection.cpp

$(PWD)/obj/lateralcontrol_multiple.o: $(PWD)/src/LaneDetection_and_Control/lateralcontrol_multiple.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(PWD)/obj/lateralcontrol_multiple.o $(PWD)/src/LaneDetection_and_Control/lateralcontrol_multiple.cpp

$(PWD)/obj/utils.o: $(PWD)/src/cpp_vrep_api/utils.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(PWD)/obj/utils.o $(PWD)/src/cpp_vrep_api/utils.cpp

$(PWD)/obj/extApi.o: $(PWD)/externalApps/vrep/programming/remoteApi/extApi.c externalApps/vrep/programming/remoteApi/extApi.h \
		externalApps/vrep/programming/remoteApi/extApiPlatform.h \
		externalApps/vrep/programming/remoteApi/extApiInternal.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o $(PWD)/obj/extApi.o $(PWD)/externalApps/vrep/programming/remoteApi/extApi.c

$(PWD)/obj/extApiPlatform.o: $(PWD)/externalApps/vrep/programming/remoteApi/extApiPlatform.c externalApps/vrep/programming/remoteApi/extApiPlatform.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o $(PWD)/obj/extApiPlatform.o $(PWD)/externalApps/vrep/programming/remoteApi/extApiPlatform.c

$(PWD)/obj/shared_memory.o: $(PWD)/externalApps/vrep/programming/common/shared_memory.c 
	$(CC) -c $(CFLAGS) $(INCPATH) -o $(PWD)/obj/shared_memory.o $(PWD)/externalApps/vrep/programming/common/shared_memory.c

####### Install

install_target: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/lib/ || $(MKDIR) $(INSTALL_ROOT)/usr/lib/ 
	-$(INSTALL_PROGRAM) "$(QMAKE_TARGET)" "$(INSTALL_ROOT)/usr/lib/$(QMAKE_TARGET)"
	-$(STRIP) "$(INSTALL_ROOT)/usr/lib/$(QMAKE_TARGET)"

uninstall_target:  FORCE
	-$(DEL_FILE) "$(INSTALL_ROOT)/usr/lib/$(QMAKE_TARGET)"
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/lib/ 


install:  install_target  FORCE

uninstall: uninstall_target   FORCE

FORCE:

